Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -115,7 +115,7 @@ jobs:
           done
           echo ""
 
-          echo "Quota: " $(/usr/local/hpcc/bin/quota-scripts/userquota.py)
+          /usr/local/hpcc/bin/quota-scripts/userquota.py || echo "quota failed"
           echo ""
           echo "===== Detailed Job Table ====="
 
